# Generated by Django 5.2.7 on 2025-12-30 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Destination Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price (€)')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount (%)')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Phone')),
                ('nb_personnes', models.PositiveIntegerField(verbose_name='Number of People')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Booking Date')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='visite.destination', verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
